#!/bin/bash

FILE=pre-commit-config

if [ ! -f $FILE ]; then
   echo "File $FILE does not exist."
fi

source $FILE

if [ -n "$PHPCS_COMMAND" ]; then
    PHPCS_OUTPUT=$($PHPCS_COMMAND)
    PHPCS_RETVAL=$?

    if [ $PHPCS_RETVAL -ne 0 ]; then
        echo "======================================="
	    echo "              PHPCS Errors             "
	    echo "======================================="
        echo "$PHPCS_OUTPUT"
        exit 1
    fi
fi


if [ -n "$PHPMD_COMMAND" ]; then
    PHPMD_OUTPUT=$($PHPMD_COMMAND)
    PHPMD_RETVAL=$?

    if [ $PHPMD_RETVAL -ne 0 ]; then
        echo "======================================="
	    echo "              PHPMD Errors             "
	    echo "======================================="
        echo "$PHPMD_OUTPUT"
        exit 1
    fi
fi

if [ -n "$PHPUNIT_COMMAND" ]; then
    PHPUNIT_OUTPUT=$($PHPUNIT_COMMAND)
    PHPUNIT_RETVAL=$?

    if [ $PHPUNIT_RETVAL -ne 0 ]; then
        echo "======================================="
	    echo "            PHPUNIT Errors             "
	    echo "======================================="
        echo "$PHPUNIT_OUTPUT"
        exit 1
    fi
fi

if [ -n "$DRUPALCHECK_COMMAND" ]; then
    DRUPALCHECK_OUTPUT=$($DRUPALCHECK_COMMAND)
    DRUPALCHECK_RETVAL=$?

    if [ $DRUPALCHECK_RETVAL -ne 0 ]; then
        echo "======================================="
	    echo "            DRUPALCHECK Errors             "
	    echo "======================================="
        echo "$DRUPALCHECK_OUTPUT"
        exit 1
    fi
fi

if [ -n "$SYMFONYSECURITY_COMMAND" ]; then
    SYMFONYSECURITY_OUTPUT=$($SYMFONYSECURITY_COMMAND)
    SYMFONYSECURITY_RETVAL=$?

    if [ $SYMFONYSECURITY_RETVAL -ne 0 ]; then
        echo "======================================="
	    echo "            SYMFONYSECURITY Errors             "
	    echo "======================================="
        echo "$SYMFONYSECURITY_OUTPUT"
        exit 1
    fi
fi

if [ -n "$SCSS_LINT_COMMAND" ]; then
    SCSS_LINT_OUTPUT=$($SCSS_LINT_COMMAND)
    SCSS_LINT_RETVAL=$?

    if [ $SCSS_LINT_RETVAL -ne 0 ]; then
        echo "======================================="
	    echo "                SCSS Lint              "
	    echo "======================================="
        echo "$SCSS_LINT_OUTPUT"
        exit 1
    fi
fi

if [ -n "$STYLELINT_COMMAND" ]; then
    STYLELINT_OUTPUT=$($STYLELINT_COMMAND)
    STYLELINT_RETVAL=$?

    if [ $STYLELINT_RETVAL -ne 0 ]; then
        echo "======================================="
	    echo "              STYLELINT_COMMAND Errors           "
	    echo "======================================="
        echo "$STYLELINT_OUTPUT"
        exit 1
    fi
fi

if [ -n "$CYPRESS_COMMAND" ]; then
    CYPRESS_OUTPUT=$($CYPRESS_COMMAND)
    CYPRESS_RETVAL=$?

    if [ $CYPRESS_RETVAL -ne 0 ]; then
        echo "======================================="
	    echo "              CYPRESS Errors           "
	    echo "======================================="
        echo "$CYPRESS_OUTPUT"
        exit 1
    fi
fi

if [ -n "$ESLINT_COMMAND" ]; then
    ESLINT_OUTPUT=$($ESLINT_COMMAND)
    ESLINT_RETVAL=$?

    if [ $ESLINT_RETVAL -ne 0 ]; then
        echo "======================================="
	    echo "              ESLINT Errors           "
	    echo "======================================="
        echo "$ESLINT_OUTPUT"
        exit 1
    fi
fi
